package com.tamper.mymail.dao;

import com.tamper.mymail.models.HmAccounts;
import org.springframework.stereotype.Repository;

@Repository
public interface HmAccountsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_accounts
     *
     * @mbggenerated
     */
    int insert(HmAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_accounts
     *
     * @mbggenerated
     */
    int insertSelective(HmAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_accounts
     *
     * @mbggenerated
     */
    HmAccounts selectByPrimaryKey(Integer accountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_accounts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(HmAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_accounts
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(HmAccounts record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_accounts
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(HmAccounts record);

    HmAccounts selectByAddress(String address);
}