package com.tamper.mymail.models;

import java.util.Date;

public class HmAccounts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountid
     *
     * @mbggenerated
     */
    private Integer accountid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountdomainid
     *
     * @mbggenerated
     */
    private Integer accountdomainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountadminlevel
     *
     * @mbggenerated
     */
    private Byte accountadminlevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountaddress
     *
     * @mbggenerated
     */
    private String accountaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountpassword
     *
     * @mbggenerated
     */
    private String accountpassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountactive
     *
     * @mbggenerated
     */
    private Byte accountactive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountisad
     *
     * @mbggenerated
     */
    private Byte accountisad;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountaddomain
     *
     * @mbggenerated
     */
    private String accountaddomain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountadusername
     *
     * @mbggenerated
     */
    private String accountadusername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountmaxsize
     *
     * @mbggenerated
     */
    private Integer accountmaxsize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountvacationmessageon
     *
     * @mbggenerated
     */
    private Byte accountvacationmessageon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountvacationsubject
     *
     * @mbggenerated
     */
    private String accountvacationsubject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountpwencryption
     *
     * @mbggenerated
     */
    private Byte accountpwencryption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountforwardenabled
     *
     * @mbggenerated
     */
    private Byte accountforwardenabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountforwardaddress
     *
     * @mbggenerated
     */
    private String accountforwardaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountforwardkeeporiginal
     *
     * @mbggenerated
     */
    private Byte accountforwardkeeporiginal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountenablesignature
     *
     * @mbggenerated
     */
    private Byte accountenablesignature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountlastlogontime
     *
     * @mbggenerated
     */
    private Date accountlastlogontime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountvacationexpires
     *
     * @mbggenerated
     */
    private Byte accountvacationexpires;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountvacationexpiredate
     *
     * @mbggenerated
     */
    private Date accountvacationexpiredate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountpersonfirstname
     *
     * @mbggenerated
     */
    private String accountpersonfirstname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountpersonlastname
     *
     * @mbggenerated
     */
    private String accountpersonlastname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountvacationmessage
     *
     * @mbggenerated
     */
    private String accountvacationmessage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountsignatureplaintext
     *
     * @mbggenerated
     */
    private String accountsignatureplaintext;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_accounts.accountsignaturehtml
     *
     * @mbggenerated
     */
    private String accountsignaturehtml;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_accounts
     *
     * @mbggenerated
     */
    public HmAccounts(Integer accountid, Integer accountdomainid, Byte accountadminlevel, String accountaddress, String accountpassword, Byte accountactive, Byte accountisad, String accountaddomain, String accountadusername, Integer accountmaxsize, Byte accountvacationmessageon, String accountvacationsubject, Byte accountpwencryption, Byte accountforwardenabled, String accountforwardaddress, Byte accountforwardkeeporiginal, Byte accountenablesignature, Date accountlastlogontime, Byte accountvacationexpires, Date accountvacationexpiredate, String accountpersonfirstname, String accountpersonlastname, String accountvacationmessage, String accountsignatureplaintext, String accountsignaturehtml) {
        this.accountid = accountid;
        this.accountdomainid = accountdomainid;
        this.accountadminlevel = accountadminlevel;
        this.accountaddress = accountaddress;
        this.accountpassword = accountpassword;
        this.accountactive = accountactive;
        this.accountisad = accountisad;
        this.accountaddomain = accountaddomain;
        this.accountadusername = accountadusername;
        this.accountmaxsize = accountmaxsize;
        this.accountvacationmessageon = accountvacationmessageon;
        this.accountvacationsubject = accountvacationsubject;
        this.accountpwencryption = accountpwencryption;
        this.accountforwardenabled = accountforwardenabled;
        this.accountforwardaddress = accountforwardaddress;
        this.accountforwardkeeporiginal = accountforwardkeeporiginal;
        this.accountenablesignature = accountenablesignature;
        this.accountlastlogontime = accountlastlogontime;
        this.accountvacationexpires = accountvacationexpires;
        this.accountvacationexpiredate = accountvacationexpiredate;
        this.accountpersonfirstname = accountpersonfirstname;
        this.accountpersonlastname = accountpersonlastname;
        this.accountvacationmessage = accountvacationmessage;
        this.accountsignatureplaintext = accountsignatureplaintext;
        this.accountsignaturehtml = accountsignaturehtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_accounts
     *
     * @mbggenerated
     */
    public HmAccounts() {
        super();
    }

    public HmAccounts(String username, String password) {
        this.accountaddress = username;
        this.accountpassword = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountid
     *
     * @return the value of hm_accounts.accountid
     *
     * @mbggenerated
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountid
     *
     * @param accountid the value for hm_accounts.accountid
     *
     * @mbggenerated
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountdomainid
     *
     * @return the value of hm_accounts.accountdomainid
     *
     * @mbggenerated
     */
    public Integer getAccountdomainid() {
        return accountdomainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountdomainid
     *
     * @param accountdomainid the value for hm_accounts.accountdomainid
     *
     * @mbggenerated
     */
    public void setAccountdomainid(Integer accountdomainid) {
        this.accountdomainid = accountdomainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountadminlevel
     *
     * @return the value of hm_accounts.accountadminlevel
     *
     * @mbggenerated
     */
    public Byte getAccountadminlevel() {
        return accountadminlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountadminlevel
     *
     * @param accountadminlevel the value for hm_accounts.accountadminlevel
     *
     * @mbggenerated
     */
    public void setAccountadminlevel(Byte accountadminlevel) {
        this.accountadminlevel = accountadminlevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountaddress
     *
     * @return the value of hm_accounts.accountaddress
     *
     * @mbggenerated
     */
    public String getAccountaddress() {
        return accountaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountaddress
     *
     * @param accountaddress the value for hm_accounts.accountaddress
     *
     * @mbggenerated
     */
    public void setAccountaddress(String accountaddress) {
        this.accountaddress = accountaddress == null ? null : accountaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountpassword
     *
     * @return the value of hm_accounts.accountpassword
     *
     * @mbggenerated
     */
    public String getAccountpassword() {
        return accountpassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountpassword
     *
     * @param accountpassword the value for hm_accounts.accountpassword
     *
     * @mbggenerated
     */
    public void setAccountpassword(String accountpassword) {
        this.accountpassword = accountpassword == null ? null : accountpassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountactive
     *
     * @return the value of hm_accounts.accountactive
     *
     * @mbggenerated
     */
    public Byte getAccountactive() {
        return accountactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountactive
     *
     * @param accountactive the value for hm_accounts.accountactive
     *
     * @mbggenerated
     */
    public void setAccountactive(Byte accountactive) {
        this.accountactive = accountactive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountisad
     *
     * @return the value of hm_accounts.accountisad
     *
     * @mbggenerated
     */
    public Byte getAccountisad() {
        return accountisad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountisad
     *
     * @param accountisad the value for hm_accounts.accountisad
     *
     * @mbggenerated
     */
    public void setAccountisad(Byte accountisad) {
        this.accountisad = accountisad;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountaddomain
     *
     * @return the value of hm_accounts.accountaddomain
     *
     * @mbggenerated
     */
    public String getAccountaddomain() {
        return accountaddomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountaddomain
     *
     * @param accountaddomain the value for hm_accounts.accountaddomain
     *
     * @mbggenerated
     */
    public void setAccountaddomain(String accountaddomain) {
        this.accountaddomain = accountaddomain == null ? null : accountaddomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountadusername
     *
     * @return the value of hm_accounts.accountadusername
     *
     * @mbggenerated
     */
    public String getAccountadusername() {
        return accountadusername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountadusername
     *
     * @param accountadusername the value for hm_accounts.accountadusername
     *
     * @mbggenerated
     */
    public void setAccountadusername(String accountadusername) {
        this.accountadusername = accountadusername == null ? null : accountadusername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountmaxsize
     *
     * @return the value of hm_accounts.accountmaxsize
     *
     * @mbggenerated
     */
    public Integer getAccountmaxsize() {
        return accountmaxsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountmaxsize
     *
     * @param accountmaxsize the value for hm_accounts.accountmaxsize
     *
     * @mbggenerated
     */
    public void setAccountmaxsize(Integer accountmaxsize) {
        this.accountmaxsize = accountmaxsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountvacationmessageon
     *
     * @return the value of hm_accounts.accountvacationmessageon
     *
     * @mbggenerated
     */
    public Byte getAccountvacationmessageon() {
        return accountvacationmessageon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountvacationmessageon
     *
     * @param accountvacationmessageon the value for hm_accounts.accountvacationmessageon
     *
     * @mbggenerated
     */
    public void setAccountvacationmessageon(Byte accountvacationmessageon) {
        this.accountvacationmessageon = accountvacationmessageon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountvacationsubject
     *
     * @return the value of hm_accounts.accountvacationsubject
     *
     * @mbggenerated
     */
    public String getAccountvacationsubject() {
        return accountvacationsubject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountvacationsubject
     *
     * @param accountvacationsubject the value for hm_accounts.accountvacationsubject
     *
     * @mbggenerated
     */
    public void setAccountvacationsubject(String accountvacationsubject) {
        this.accountvacationsubject = accountvacationsubject == null ? null : accountvacationsubject.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountpwencryption
     *
     * @return the value of hm_accounts.accountpwencryption
     *
     * @mbggenerated
     */
    public Byte getAccountpwencryption() {
        return accountpwencryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountpwencryption
     *
     * @param accountpwencryption the value for hm_accounts.accountpwencryption
     *
     * @mbggenerated
     */
    public void setAccountpwencryption(Byte accountpwencryption) {
        this.accountpwencryption = accountpwencryption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountforwardenabled
     *
     * @return the value of hm_accounts.accountforwardenabled
     *
     * @mbggenerated
     */
    public Byte getAccountforwardenabled() {
        return accountforwardenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountforwardenabled
     *
     * @param accountforwardenabled the value for hm_accounts.accountforwardenabled
     *
     * @mbggenerated
     */
    public void setAccountforwardenabled(Byte accountforwardenabled) {
        this.accountforwardenabled = accountforwardenabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountforwardaddress
     *
     * @return the value of hm_accounts.accountforwardaddress
     *
     * @mbggenerated
     */
    public String getAccountforwardaddress() {
        return accountforwardaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountforwardaddress
     *
     * @param accountforwardaddress the value for hm_accounts.accountforwardaddress
     *
     * @mbggenerated
     */
    public void setAccountforwardaddress(String accountforwardaddress) {
        this.accountforwardaddress = accountforwardaddress == null ? null : accountforwardaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountforwardkeeporiginal
     *
     * @return the value of hm_accounts.accountforwardkeeporiginal
     *
     * @mbggenerated
     */
    public Byte getAccountforwardkeeporiginal() {
        return accountforwardkeeporiginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountforwardkeeporiginal
     *
     * @param accountforwardkeeporiginal the value for hm_accounts.accountforwardkeeporiginal
     *
     * @mbggenerated
     */
    public void setAccountforwardkeeporiginal(Byte accountforwardkeeporiginal) {
        this.accountforwardkeeporiginal = accountforwardkeeporiginal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountenablesignature
     *
     * @return the value of hm_accounts.accountenablesignature
     *
     * @mbggenerated
     */
    public Byte getAccountenablesignature() {
        return accountenablesignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountenablesignature
     *
     * @param accountenablesignature the value for hm_accounts.accountenablesignature
     *
     * @mbggenerated
     */
    public void setAccountenablesignature(Byte accountenablesignature) {
        this.accountenablesignature = accountenablesignature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountlastlogontime
     *
     * @return the value of hm_accounts.accountlastlogontime
     *
     * @mbggenerated
     */
    public Date getAccountlastlogontime() {
        return accountlastlogontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountlastlogontime
     *
     * @param accountlastlogontime the value for hm_accounts.accountlastlogontime
     *
     * @mbggenerated
     */
    public void setAccountlastlogontime(Date accountlastlogontime) {
        this.accountlastlogontime = accountlastlogontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountvacationexpires
     *
     * @return the value of hm_accounts.accountvacationexpires
     *
     * @mbggenerated
     */
    public Byte getAccountvacationexpires() {
        return accountvacationexpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountvacationexpires
     *
     * @param accountvacationexpires the value for hm_accounts.accountvacationexpires
     *
     * @mbggenerated
     */
    public void setAccountvacationexpires(Byte accountvacationexpires) {
        this.accountvacationexpires = accountvacationexpires;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountvacationexpiredate
     *
     * @return the value of hm_accounts.accountvacationexpiredate
     *
     * @mbggenerated
     */
    public Date getAccountvacationexpiredate() {
        return accountvacationexpiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountvacationexpiredate
     *
     * @param accountvacationexpiredate the value for hm_accounts.accountvacationexpiredate
     *
     * @mbggenerated
     */
    public void setAccountvacationexpiredate(Date accountvacationexpiredate) {
        this.accountvacationexpiredate = accountvacationexpiredate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountpersonfirstname
     *
     * @return the value of hm_accounts.accountpersonfirstname
     *
     * @mbggenerated
     */
    public String getAccountpersonfirstname() {
        return accountpersonfirstname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountpersonfirstname
     *
     * @param accountpersonfirstname the value for hm_accounts.accountpersonfirstname
     *
     * @mbggenerated
     */
    public void setAccountpersonfirstname(String accountpersonfirstname) {
        this.accountpersonfirstname = accountpersonfirstname == null ? null : accountpersonfirstname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountpersonlastname
     *
     * @return the value of hm_accounts.accountpersonlastname
     *
     * @mbggenerated
     */
    public String getAccountpersonlastname() {
        return accountpersonlastname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountpersonlastname
     *
     * @param accountpersonlastname the value for hm_accounts.accountpersonlastname
     *
     * @mbggenerated
     */
    public void setAccountpersonlastname(String accountpersonlastname) {
        this.accountpersonlastname = accountpersonlastname == null ? null : accountpersonlastname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountvacationmessage
     *
     * @return the value of hm_accounts.accountvacationmessage
     *
     * @mbggenerated
     */
    public String getAccountvacationmessage() {
        return accountvacationmessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountvacationmessage
     *
     * @param accountvacationmessage the value for hm_accounts.accountvacationmessage
     *
     * @mbggenerated
     */
    public void setAccountvacationmessage(String accountvacationmessage) {
        this.accountvacationmessage = accountvacationmessage == null ? null : accountvacationmessage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountsignatureplaintext
     *
     * @return the value of hm_accounts.accountsignatureplaintext
     *
     * @mbggenerated
     */
    public String getAccountsignatureplaintext() {
        return accountsignatureplaintext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountsignatureplaintext
     *
     * @param accountsignatureplaintext the value for hm_accounts.accountsignatureplaintext
     *
     * @mbggenerated
     */
    public void setAccountsignatureplaintext(String accountsignatureplaintext) {
        this.accountsignatureplaintext = accountsignatureplaintext == null ? null : accountsignatureplaintext.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_accounts.accountsignaturehtml
     *
     * @return the value of hm_accounts.accountsignaturehtml
     *
     * @mbggenerated
     */
    public String getAccountsignaturehtml() {
        return accountsignaturehtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_accounts.accountsignaturehtml
     *
     * @param accountsignaturehtml the value for hm_accounts.accountsignaturehtml
     *
     * @mbggenerated
     */
    public void setAccountsignaturehtml(String accountsignaturehtml) {
        this.accountsignaturehtml = accountsignaturehtml == null ? null : accountsignaturehtml.trim();
    }
}